name = "LatticeBoltzmann"
uuid = "b352ac26-0211-49f8-8be9-fedc9142cc32"
authors = ["Johann Albers"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
