using StaticArrays

const VELOCITIES = Dict(
    :d2q9 => SVector{3, Int}[
        SVector( 0,  0,  0),
        SVector( 1,  0,  0),
        SVector(-1,  0,  0),
        SVector( 0,  1,  0),
        SVector( 0, -1,  0),
        SVector( 1,  1,  0),
        SVector(-1, -1,  0),
        SVector( 1, -1,  0),
        SVector(-1,  1,  0)
    ],
    :d3q7 => SVector{3, Int}[
        SVector( 0,  0,  0),
        SVector( 1,  0,  0),
        SVector(-1,  0,  0),
        SVector( 0,  1,  0),
        SVector( 0, -1,  0),
        SVector( 0,  0,  1),
        SVector( 0,  0, -1)
    ],
    :d3q19 => SVector{3, Int}[
        SVector( 0,  0,  0 ),
        SVector( 1,  0,  0 ),
        SVector(-1,  0,  0 ),
        SVector( 0,  1,  0 ),
        SVector( 0, -1,  0 ),
        SVector( 0,  0,  1 ),
        SVector( 0,  0, -1 ),
        SVector( 1,  1,  0 ),
        SVector(-1, -1,  0 ),
        SVector( 1,  0,  1 ),
        SVector(-1,  0, -1 ),
        SVector( 0,  1,  1 ),
        SVector( 0, -1, -1 ),
        SVector( 1, -1,  0 ),
        SVector(-1,  1,  0 ),
        SVector( 1,  0, -1 ),
        SVector(-1,  0,  1 ),
        SVector( 0,  1, -1 ),
        SVector( 0, -1,  1 )
    ],
    :d3q27 => SVector{3, Int}[
        SVector( 0,  0,  0 ),
        SVector( 1,  0,  0 ),
        SVector(-1,  0,  0 ),
        SVector( 0,  1,  0 ),
        SVector( 0, -1,  0 ),
        SVector( 0,  0,  1 ),
        SVector( 0,  0, -1 ),
        SVector( 1,  1,  0 ),
        SVector(-1, -1,  0 ),
        SVector( 1,  0,  1 ),
        SVector(-1,  0, -1 ),
        SVector( 0,  1,  1 ),
        SVector( 0, -1, -1 ),
        SVector( 1, -1,  0 ),
        SVector(-1,  1,  0 ),
        SVector( 1,  0, -1 ),
        SVector(-1,  0,  1 ),
        SVector( 0,  1, -1 ),
        SVector( 0, -1,  1 ),
        SVector( 1,  1,  1 ),
        SVector(-1, -1, -1 ),
        SVector( 1,  1, -1 ),
        SVector(-1, -1,  1 ),
        SVector( 1, -1,  1 ),
        SVector(-1,  1, -1 ),
        SVector(-1,  1,  1 ),
        SVector( 1, -1, -1 )
    ]
)